### ISSUE TITLE
Copy a Glyph from one project to another (Universal Copy)

### ISSUE THREAD

**Issue by CitizenFoffie** [glyphr-studio/Glyphr-Studio-1#287]
I'm trying to copy a letter of one font to send it to another, How do I do this (example. I like the D of one font, and I want it as the D of my font.)

**Comment by mattlag** [comment]
At the moment, individual Glyphr Studio Projects can't talk to each other.  This is something i'm going to resolve as I slowly work on Glyphr Studio v2.  

For now, it's only really possible if you are comfortable editing JSON text documents.  If you save both of your fonts as a Glyphr Studio Project text files, you can copy/paste a single Glyph object from one to the other.  There are many things that can go wrong with this :-)

I'm going to change the title of this, because I think if anything happens in Glyphr Studio v1, it will be something more like having your two fonts open in two browser tabs, then having some sort of Import / Export Glyph action.  I will think about it.

**Comment by CitizenFoffie** [comment]
Thank you for answering.

**Comment by mattlag** [comment]
Import SVG directly to Canvas just shipped with v1.13 - i'm thinking if there was an easy way to just save a single glyph as SVG, then this scenario could be completed...

**Comment by mattlag** [comment]
Closing all v1 issues that will be addressed in v2.
