### ISSUE TITLE
export font svg

### ISSUE THREAD

**Issue by ghost** [glyphr-studio/Glyphr-Studio-1#324]
click export, toast msg comes up and goes away. nothing else happens.
windows 10 64, ver 20h2
tried on firefox,chrome,and edge.

as far as i can tell no file was saved or opened or anything.
firefox has a bunch of extensions, chrome has no script (which I disabled), edge is factory default.
am i playing my "i am really stupid old man" card?

**Comment by mattlag** [comment]
Hey! Sounds like an error is causing the export to fail. Could you attach your project file? I can turn on extended debugging in my dev environment and figure out exactly what's going on.

**Comment by trsBasicLine10** [comment]
can do, thanks for the response.
[FRD Stencil Bold Plasma - Glyphr Project - 2021.5.30-21.57.02.txt](https://github.com/glyphr-studio/Glyphr-Studio-1/files/6567631/FRD.Stencil.Bold.Plasma.-.Glyphr.Project.-.2021.5.30-21.57.02.txt)

**Comment by trsBasicLine10** [comment]
I would like to say that I like your app. I have been trying for a couple of weeks to figure out font forge to make a font for my brother-in-law with proper gaps for his plasma cutter.

**Comment by trsBasicLine10** [comment]
I have tried to export just a 2 or 3 simple shapes in a single letter and the svg export does not do anything except the toast message.

**Comment by mattlag** [comment]
Hello!  Just now getting around to looking into this.  The SVG Font export worked fine for me.  The expected behavior is you'll see one toast message, then it will disappear.  All exported files go to your browser's downloads folder - you can customize what folder is your downloads folder, but on windows the default is just the folder called "Downloads" :-)  Since this is a browser based app, there is no true file system integration... the only location available to put new files is the downloads folder.

Take a look there to see if you have your exports!

**Comment by trsBasicLine10** [comment]
I have started a couple of new projects and just did a couple of letters. I
again tried on firefox (lots of extension), Chrome (only a couple of
extensions), and the edge browser (no mods) and i get nothing in the
downloads folder. I get it is probably something to do with windows or even
my windows. I will just use fontforge with its quirks. thanks for looking
into it. neat idea and execution. browser apps has a ways to go yet.
