### ISSUE TITLE
Apostrophe and Quotation marks not working.

### ISSUE THREAD

**Issue by kalimx** [glyphr-studio/Glyphr-Studio-1#326]
Hi,

I have made glyphs for both an apostrophe and quotation marks, but when I try to use the font in MS Word they don't show up.
When I press the relevant buttons on the keyboard it prints the characters in the Courier New font. They are however in the character set when I go to insert > more symbols. 

What could be causing this?

Thanks.

**Comment by mattlag** [comment]
Hello!  This is a very common problem - most word processors go in and replace Quotation Mark and Apostrophe with their curly beginning and end equivalents.  There are not keys on your keyboard for the curly ones, but because your word processor tries to help you by automatically replacing them, it makes it look weird if you do not have those characters designed in your font.

Go into Glyphr Studio menu > Font Settings and scroll down to "Additional glyph ranges" section.  There you can find and enable the General Punctuation Range starting at 0x2000

![image](https://user-images.githubusercontent.com/5897669/131382045-f3b3cace-2b98-4cb3-b437-80ee86b1b93d.png)

After that there are probably at least 4 characters you want to design
 - Left single quotation mark
 - Right single quotation mark
 - Left double quotation mark
 - Right double quotation mark

![image](https://user-images.githubusercontent.com/5897669/131382415-0a642e16-caac-4b3c-b803-220006e7c807.png)

I believe these should handle all the auto-replacement behaviors for your word processor.

As a side note, if you want the curly quotes to look the same as the straight ones, you could go to the curly characters and add the straight version as a Component - that way if you update the straight ones the designs will be connected so you don't have to copy / paste the designs each time.
