### ISSUE TITLE
Saving option desktop version: Glyphr Studio Project File option error?

### ISSUE THREAD

**Issue by raoulunger** [glyphr-studio/Glyphr-Studio-1#330]
Hi,

I'm having great fun test driving Glyphr, and I think it's excellent, so thank you!! I tested both the web version and the desktop version on a Mac.

In both versions there are three options for saving the file (Glyphr Studio Project File, OTF, and SVG). According to the (again outstanding) help documentation the first option (GSPF) should result in a .txt file being saved. This is indeed true for the webversion. However, in de desktop version choosing the GSFP results in an OTF file. A .txt file is not produced.

Is this an error or intentional? If intentional it would perhaps be good to mention the difference in behaviour in the documentation.

Cheers!

**Comment by mattlag** [comment]
The client version should be able to save all 3 types of files.  But, to be honest, the desktop app was kind of an experiment, managed by a separate team (it's basically wrapping the web version, minus some features, into an app with Electron).

So, I have two recommendations - one is that the web version actually has more features than the desktop version, and is updated more often, so it's recommended to use that, really.

The other action would be to open an issue in Glyphr-Studio-Desktop and see if the maintainers can look into the issue:
https://github.com/glyphr-studio/Glyphr-Studio-Desktop  because this does sound like an error, a .txt file should be able to be saved.

**Comment by raoulunger** [comment]
Hi,

Thanks for the quick respons. I'll stick to the web version then; i did notice there were some slight differences in functionality. For good measure i'll also mention the issue on the other github-account, I had not noticed there were two.

Cheers!

**Comment by mattlag** [comment]
Sounds good!
