### ISSUE TITLE
Ghost Pre/Post Chars

### ISSUE THREAD

**Issue by mattlag** [glyphr-studio/Glyphr-Studio-1#6]
show characters inline (to the left or right) of the character you are currently editing

Work could be done as part of Kerning work item

**Comment by davelab6** [comment]
This is also something I discussed in https://github.com/mattlag/Glyphr-Studio/issues/94 and I think its quite high priority for making glyphr productive :)

![byp6dfliyaegmql](https://cloud.githubusercontent.com/assets/261579/4800618/2431afe8-5e28-11e4-937c-06cd5b020f01.png)

**Comment by mattlag** [comment]
This shouldn't be that hard, most of the code changes to enable this happened with the Kerning updates.  I think Multiselect points / shapes is higher pri, so i'm tentatively slating this for v1.02

**Comment by davelab6** [comment]
Agree that is the most important thing right now. Second for me is not being able seeing Test Drive concurrently with Glyph Edit (using 2 window mode). And 3rd is this issue - being able to see several glyphs next to each other, and edit their spacing. 

While the above image uses a classic spacing table, as seen in Fontographer, Fontlab, FontForge, and RoboFont, Glyphs uses a floating palette for the actively editing glyph (only) in the 'ghost' view this issue is about. There seems to be no way to see the metrics as a table in Glyphs.  

![edit-iceberg](https://cloud.githubusercontent.com/assets/261579/7577568/a1df310a-f841-11e4-845b-2d3e3031eb4b.png)

- https://www.glyphsapp.com/tutorials/edit-view

So the classic table clearly isn't the only way to do this. 

Over on the Metapolator wiki, @guiguru has proposed a new way of editing widths and sidebearings: 

https://github.com/metapolator/metapolator/wiki/specimen,-and-glyph-interaction#editing-width-and-sidebearings

**Comment by mattlag** [comment]
Cool - thanks for the examples!

**Comment by mattlag** [comment]
Initial implementation in v1.09, further improvements coming soon.  Closing this to clean up.
